### ISSUE TITLE
Use cases?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-fileio#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/intro-to-file-io?module_item_id=467995

### Concern

It's hard to understand what the purpose of File I/O is based on this reading.

### Suggested Changes

Can we include some practical use cases for using this, or explain the necessity? We give a very brief, generic explanation at the beginning, but it would be helpful for students to have a more concrete idea of why they're learning this material. Right now, the information seems kind of arbitrary, and it's hard to understand how we would use this in a program.

**Comment by professor-ben** [comment]
Thanks for the feedback! I'm working on this lesson right now, so I'll make sure that more use cases are addressed.
